/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package my_package;

/**
 *
 * @author 22.01519-0
 */
public class ProductPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductPanel
     */
    public ProductPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productText = new javax.swing.JTextField();
        qtdText = new javax.swing.JTextField();
        priceText = new javax.swing.JTextField();
        unitPv = new javax.swing.JTextField();
        totalValue = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        qtdChanged = new javax.swing.JTextField();
        totalPv = new javax.swing.JTextField();

        

        productText.setText("Product Name");
        productText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productTextActionPerformed(evt);
            }
        });

        qtdText.setText("Qtd");
        qtdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdTextActionPerformed(evt);
            }
        });

        priceText.setText("Price per Product");
        priceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextActionPerformed(evt);
            }
        });

        unitPv.setText("Unit Pv");
        unitPv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryTextActionPerformed(evt);
            }
        });

        totalValue.setText("Total Value");
        totalValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitTextActionPerformed(evt);
            }
        });

        date.setText("Entry ou Exit Date");
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryText1ActionPerformed(evt);
            }
        });

        qtdChanged.setText("Qtd added or sub");
        qtdChanged.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitText1ActionPerformed(evt);
            }
        });

        totalPv.setText("Total Pv");
        totalPv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitText2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(productText, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(qtdText, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unitPv, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdChanged, javax.swing.GroupLayout.PREFERRED_SIZE, 128 ,javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPv, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalValue, javax.swing.GroupLayout.DEFAULT_SIZE,128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtdText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitPv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtdChanged, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
                
        );
        setEditableFalse();
        repaint();
        revalidate();
    }// </editor-fold>//GEN-END:initComponents

    private void productTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productTextActionPerformed

    private void priceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextActionPerformed

    private void entryTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryTextActionPerformed

    private void qtdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtdTextActionPerformed

    private void exitTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitTextActionPerformed

    private void entryText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryText1ActionPerformed

    private void exitText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitText1ActionPerformed

    private void exitText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitText2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField unitPv;
    private javax.swing.JTextField date;
    private javax.swing.JTextField totalValue;
    private javax.swing.JTextField qtdChanged;
    private javax.swing.JTextField totalPv;
    private javax.swing.JTextField priceText;
    private javax.swing.JTextField productText;
    private javax.swing.JTextField qtdText;
    // End of variables declaration//GEN-END:variables
    public void setEditable() {
        productText.setEditable(true);
        qtdText.setEditable(true);
        priceText.setEditable(true);
        unitPv.setEditable(true);
        totalValue.setEditable(true);
        date.setEditable(true);
        qtdChanged.setEditable(true);
        totalPv.setEditable(true);
    }

    /**
     * Define os campos como não editáveis.
     */
    public void setEditableFalse() {
        productText.setEditable(false);
        productText.setFocusable(false);
    
        qtdText.setEditable(false);
        qtdText.setFocusable(false);
    
        priceText.setEditable(false);
        priceText.setFocusable(false);
    
        unitPv.setEditable(false);
        unitPv.setFocusable(false);
    
        totalValue.setEditable(false);
        totalValue.setFocusable(false);
    
        date.setEditable(false);
        date.setFocusable(false);
    
        qtdChanged.setEditable(false);
        qtdChanged.setFocusable(false);
    
        totalPv.setEditable(false);
        totalPv.setFocusable(false);
    }
    

    /**
     * Atualiza os textos dos campos com os valores fornecidos.
     */
    public void setText(String produ, String qtd, String price, String totalPvValue, 
                        String qtdAddSubValue, String totalValueText, String dateText, String unitPvText) {
        productText.setText(produ);
        qtdText.setText(qtd);
        priceText.setText(price);
        totalPv.setText(totalPvValue);
        qtdChanged.setText(qtdAddSubValue);
        totalValue.setText(totalValueText);
        date.setText(dateText);
        unitPv.setText(unitPvText);
    }
    
}
